name = "halal-directory-site"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "halal-directory"
database_id = "6b8e0660-9ef2-48d1-aaf9-2ea87bbfb793"
